### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by andreasbaumann** [mb21/bildungsgeschichte.ch#1]
Your PATH must contain the `node_modules/.bin` folder otherwise `yarn build` says that `react-snap` is not found.

`yarn build` results in 

$ react-snap
error Command failed with exit code 1.

No indication of errors whatsoverer.

The `build/` directory contains only a 200.html, no 404.html, no de/fr/it/en

**Comment by andreasbaumann** [comment]
Tried on Archlinux, npm version 6.9.0, yarn version 1.15.2.

**Comment by mb21** [comment]
You sure you did a `yarn install` first?

**Comment by andreasbaumann** [comment]
yes, I am. `yarn install`, then `yarn build`. The build runs and does something, also
`react-snap` runs, but it exits with exit code 1.

On what Linux did you use it, maybe Archlinux is too bleeding edge? :-)

**Comment by mb21** [comment]
I just tried on a relatively freshly installed mac and that works... `react-snap` is only used for prerendering a few pages, but for that I think it spins up a whole Chrome instance...

**Comment by andreasbaumann** [comment]
Also tried on a Mac with brew, works fine.

I think, something is wrong with puppeteer and chromium on Archlinux (maybe a sandboxing issue)..

**Comment by andreasbaumann** [comment]
Aha: I have to set: `sysctl -w kernel.unprivileged_userns_clone=1`.
